# frozen_string_literal: true

module Api
  module V2
    class RangesController < ApplicationController
      NUMERIC_COLUMNS = %i[
        tempf humidity windspeedmph windgustmph maxdailygust winddir
        uv solarradiation hourlyrainin dailyrainin weeklyrainin
        monthlyrainin totalrainin battout tempinf humidityin
        baromrelin baromabsin batt_co2
      ].freeze

      def show
        start_date = Time.iso8601(params.fetch(:start_date))
        end_date   = Time.iso8601(params.fetch(:end_date))
        segments   = Integer(params.fetch(:segments, 100))

        if end_date <= start_date
          return render json: {
            error: 'end_date must be after start_date'
          }, status: :bad_request
        end

        unless segments.between?(1, 500)
          return render json: {
            error: 'Segments must be between 1 and 500'
          }, status: :bad_request
        end

        duration = end_date.to_f - start_date.to_f
        seconds_per_segment = duration / segments

        # Use a quoted timestamp generated by the database adapter rather
        # than interpolating the raw request parameter.
        quoted_start = WeatherSnapshot.connection.quote(start_date)

        avg_sql = NUMERIC_COLUMNS
                    .map { |column| "AVG(#{column}) AS #{column}" }
                    .join(', ')

        segment_sql = <<~SQL.squish
          FLOOR(
            EXTRACT(EPOCH FROM (dateutc - #{quoted_start}))
            / #{seconds_per_segment}
          ) AS segment_index,
          MIN(dateutc) AS first_datetime,
          MAX(dateutc) AS last_datetime
        SQL

        results = WeatherSnapshot
                    .select("#{avg_sql}, #{segment_sql}")
                    .where(dateutc: start_date..end_date)
                    .group('segment_index')
                    .order('segment_index')

        output = results.map do |row|
          segment_index = row.segment_index.to_i

          segment_start =
            start_date + segment_index * seconds_per_segment

          segment_end =
            [start_date + (segment_index + 1) * seconds_per_segment, end_date].min

          midpoint_start = row.first_datetime || segment_start
          midpoint_end   = row.last_datetime || segment_end
          segment_datetime = midpoint_start + (midpoint_end - midpoint_start) / 2

          {
            start: segment_start,
            end: segment_end,
            datetime: segment_datetime,
            averages: NUMERIC_COLUMNS.index_with do |column|
              row.public_send(column)
            end
          }
        end

        render json: output
      rescue KeyError, ArgumentError
        render json: {
          error: 'start_date and end_date must be valid ISO-8601 timestamps'
        }, status: :bad_request
      end
    end
  end
end
